# Generated by Django 3.1.6 on 2021-02-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.SmallIntegerField()),
                ('y', models.SmallIntegerField()),
                ('color', models.CharField(choices=[('W', 'White'), ('R', 'Red'), ('B', 'Blue')], max_length=1)),
            ],
        ),
    ]
