# Generated by Django 3.1.6 on 2021-02-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelfabrik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('E', 'Empty'), ('EB', 'Emptybox'), ('F', 'Full')], default='F', max_length=2),
        ),
    ]
