# Generated by Django 3.1.6 on 2021-03-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factoryWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddres',
            new_name='ShippingAddress',
        ),
    ]
