# Generated by Django 3.1.6 on 2021-03-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factoryWebsite', '0009_auto_20210326_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
    ]
