# Generated by Django 3.1.6 on 2021-03-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factoryWebsite', '0010_remove_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
