# Generated by Django 3.1.6 on 2021-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factoryWebsite', '0011_remove_orderitem_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='order',
            name='sendToFactory',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
