# Generated by Django 3.1.6 on 2021-04-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factoryWebsite', '0013_order_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
